[package]
name = "subtensor-transaction-fee"
version = "0.1.0"
edition.workspace = true

[dependencies]
codec = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
pallet-subtensor = { workspace = true }
pallet-transaction-payment = { workspace = true }
scale-info = { workspace = true }
smallvec = { workspace = true }
sp-runtime = { workspace = true }
substrate-fixed = { workspace = true }
subtensor-runtime-common = { workspace = true }

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-subtensor/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"sp-runtime/std",
	"substrate-fixed/std",
	"subtensor-runtime-common/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
