[package]
name = "subtensor-custom-rpc"
version = "0.0.2"
edition.workspace = true
authors = ['Cameron Fairchild <https://github.com/camfairchild>']
repository = 'https://github.com/opentensor/subtensor'
description = "A pallet that adds custom RPC calls to subtensor"
license = "MIT"
publish = false

[lints]
workspace = true

[dependencies]
codec = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }

# Substrate packages
sp-api.workspace = true
sp-blockchain.workspace = true
sp-runtime.workspace = true

# local packages
subtensor-runtime-common.workspace = true
subtensor-custom-rpc-runtime-api.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-runtime/std",
	"subtensor-custom-rpc-runtime-api/std",
	"subtensor-runtime-common/std",
]
pow-faucet = []
