[package]
name = "pallet-subtensor-swap"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
approx = { workspace = true }
codec = {workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
safe-math = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true, optional = true }
sp-arithmetic = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
substrate-fixed = { workspace = true }

pallet-subtensor-swap-interface = { workspace = true }

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"alloy-primitives/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-subtensor-swap-interface/std",
	"safe-math/std",
	"scale-info/std",
	"serde/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"sp-std/std",
	"substrate-fixed/std",
]
