name: Build Localnet Docker Image

on:
  pull_request:

jobs:
  build:
    runs-on: SubtensorCI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -f Dockerfile-localnet -t localnet .

      - name: Save Docker Image as Tar
        run: docker save -o subtensor-localnet.tar localnet

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: subtensor-localnet
          path: subtensor-localnet.tar
