name: Publish Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - devnet-ready
      - devnet
      - testnet

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  publish:
    runs-on: SubtensorCI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: tag
        run: |
          case "${{ github.ref_name }}" in
            devnet-ready)
              echo "tag=devnet-ready" >> $GITHUB_ENV
              ;;
            devnet)
              echo "tag=devnet" >> $GITHUB_ENV
              ;;
            testnet)
              echo "tag=testnet" >> $GITHUB_ENV
              ;;
            *)
              echo "Branch not recognized for custom tagging."
              exit 1
              ;;
          esac

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.tag }}
            ghcr.io/${{ github.repository }}:latest
