# .github/workflows/benchmarks.yml
name: Validate-Benchmarks

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

concurrency:
  group: run-benchmarks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-benchmarks:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-validate-benchmarks') }}
    runs-on: Benchmarking
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check skip label
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "Skip label found - stopping."
            exit 1
          fi

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Check skip label
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "Skip label found - stopping."
            exit 1
          fi

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Check skip label
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "Skip label found - stopping."
            exit 1
          fi

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          key: bench-${{ hashFiles('**/Cargo.lock') }}

      - name: Check skip label
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "Skip label found - stopping."
            exit 1
          fi

      - name: Build node with benchmarks
        run: |
          cargo build --profile production -p node-subtensor --features runtime-benchmarks

      - name: Check skip label
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "Skip label found - stopping."
            exit 1
          fi

      - name: Run & validate benchmarks
        run: |
          chmod +x scripts/benchmark_action.sh
          ./scripts/benchmark_action.sh
