name: Update Chainspecs

concurrency:
  group: update-chainspec-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  workflow_dispatch:
    inputs:
      verbose:
        description: "Output more information when triggered manually"
        required: false
        default: ""

env:
  CARGO_TERM_COLOR: always
  VERBOSE: ${{ github.events.input.verbose }}

jobs:
  update-chainspecs:
    runs-on: [self-hosted, type-ccx33, in-hel1]
    permissions:
      contents: write
    if: >
      github.event.pull_request.head.ref != 'devnet-ready' &&
      github.event.pull_request.head.ref != 'devnet' &&
      github.event.pull_request.head.ref != 'testnet' &&
      github.event.pull_request.head.ref != 'main'

    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y --no-install-recommends clang curl libssl-dev llvm libudev-dev protobuf-compiler pkg-config

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build chainspecs
        run: ./scripts/build_all_chainspecs.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit any updated chainspecs
        with:
          commit_message: Update chainspecs
